# 配置数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bookshop?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
<<<<<<< HEAD
    password: asd123
>>>>>>> yu
  mvc:
    servlet:
      load-on-startup: 1
      path: /
      # mybatis相关配置
    view:
      suffix: .jsp
      prefix: /
mybatis:
        # 配置别名需要扫描的包
        type-aliases-package: com.zp.entity
        # mapper映射文件
        mapper-locations: classpath:mapper/*.xml
        configuration:
          # 配置日志在控制台显示sql语句
          log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
          # 开启二级缓存
          cache-enabled: true
